<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
<title>Projet Robot - ENSICAEN</title>
<link href="css/mchp.css" rel="stylesheet" type="text/css" />
<script src="javascript/mchp.js" type="text/javascript"></script>
</head>

<body onload="newAJAXCommand('status.xml');">
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">

<div style="padding:0 0 5px 5px"><img height=100 width=100 src="images/ensicaen.gif" alt="Microchip" /></div>

<div id="title"><div class="right">Controle et commande</div><span id="hello">&nbsp;</span></div>

<div id="menu">
<a href="/index.htm">Information</a>
<a href="/initialisation.html">Configuration</a>
<a href="/upload.htm">Mise a jour</a>
<a href="/eeprom.htm">EEprom</a>
</div>
